version: "3.8"

networks:
  tor_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  entry:
    build: .
    container_name: entry-1
    command: python server.py 0 172.20.0.2
    networks:
      tor_net:
        ipv4_address: 172.20.0.2

  middle:
    build: .
    container_name: middle-1
    command: python server.py 1 172.20.0.3
    networks:
      tor_net:
        ipv4_address: 172.20.0.3
    depends_on:
      - entry

  exit:
    build: .
    container_name: exit-1
    command: python server.py 2 172.20.0.4
    networks:
      tor_net:
        ipv4_address: 172.20.0.4
    depends_on:
      - middle

  client:
    build: .
    container_name: client-1
    command: python client.py
    stdin_open: true
    tty: true
    networks:
      - tor_net
    depends_on:
      - entry
      - middle
      - exit